name: Run Ansible Playbook on Localhost

on:
  workflow_dispatch: # Enables manual triggering of the workflow
    inputs: # Optional, to define inputs for the workflow
      app_name:
        description: 'Application Name' 
        required: true 
        default: 'application1'
      github_url:
        description: 'Application URL' 
        required: true 
        default: 'https://github.com/nomanazeem/app1'
      jira_ticket:
        description: 'Ticket Number'
        required: true
        default: 'TKT-0001'
 
      branch:
        description: 'Branch to run the workflow on'
        default: 'main'
        required: false

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment for Ansible
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install Ansible
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      # Step 4: Create an inline inventory file for localhost
      - name: Create inventory for localhost
        run: |
          echo "[local]" > inventory.yml
          echo "localhost ansible_connection=local" >> inventory.yml

      # Step 5: Run Ansible Playbook on localhost
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.yml playbook.yml \
          --extra-vars "GIT_USER=${{ secrets.GHA_USER }} \
                        GIT_EMAIL=${{ secrets.GHA_EMAIL }} \
                        GIT_PAT=${{ secrets.GHA_PAT }}  \
                        app_name=${{ inputs.app_name }} \
                        jira_ticket=${{ inputs.jira_ticket }} \
                        github_url=${{ inputs.github_url }} "
 
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
